### ISSUE TITLE
if i have three changed  .c file,  use git diff create a *.diff file, how can i make a patch ?

### ISSUE THREAD

**Issue by chenzhbao629** [cloudlinux/libcare#45]
1 diff --git a/dpdkxxxxxxx/xxxxxx/vhost.c b/dpdkxxxxxxx/xxxxx/vhost.c
  2 index 3c3f6a4..36fdfb5 100644
  3 --- a/dpdkxxxxx/xxxxxx/vhost.c
  4 +++ b/dpdkxxxxxx/xxxxxxx/vhost.c
  5 
 14 diff --git a/dpdkxxxxx/xxxxxxx/vhost.h b/dpdkxxxxxx/xxxxxxx/vhost.h
 15 index 399b7bc..4c0aa80 100644
 16 --- a/dpdkxxxxxx/xxxxxx/vhost.h
 17 +++ b/dpdkxxxxx/xxxxxxx/vhost.h

 27 diff --git a/dpdkxxxxxx/xxxxxxxxxx/vhost_user.c b/dpdkxxxxxx/xxxxxxx/virtio_net.c
 28 index 395febb..5b957a0 100644
159 --- a/dpdkxxxxx/xxxxxx/virtio_net.c
160 +++ b/dpdkxxxxxx/xxxxxxx/virtio_net.c

**Comment by paboldin** [comment]
You should export the patch to a file:

$ git diff > foobar.patch

And then build it with `$LIBCARE/src/libcare-patch-make` script by passing a source patch as a file:

$ ~/libcare/src/libcare-patch-make ./foobar.patch

It should build patches and place them in `./patchroot`.

**Comment by chenzhbao629** [comment]
I had use the cmd：~/libcare/src/libcare-patch-make ./foobar.patch， but I failed,  Maybe i wrote a  mistake  makefile file.

**Comment by chenzhbao629** [comment]
I used the example,: libcare/tests/fail_threading and  ./../../src/libcare-patch-make fail_threading.diff 
**but failed**
./../../src/libcare-patch-make fail_threading.diff 
awk: cmd. line:4: warning: escape sequence `\.' treated as plain `.'
BUILDING ORIGINAL CODE
./../../src/libcare-cc     fail_threading.c  -lpthread -o fail_threading
INSTALLING ORIGINAL OBJECTS INTO /home/hanle/src/libcare/tests/fail_threading/lpmake
mkdir -p /home/hanle/src/libcare/tests/fail_threading/lpmake || :
cp ./fail_threading    /home/hanle/src/libcare/tests/fail_threading/lpmake
if test -n ""; then                             \
        cp c51f2c6da66aad6f19cde255b49383e24aa31f11.kpatch /home/hanle/src/libcare/tests/fail_threading/lpmake; \
fi
if test -n ""; then                             \
        cp -L  /home/hanle/src/libcare/tests/fail_threading/lpmake;\
fi
applying fail_threading.diff...
patching file fail_threading.c
BUILDING PATCHED CODE
./../../src/libcare-cc     fail_threading.c  -lpthread -o fail_threading
INSTALLING PATCHED OBJECTS INTO /home/hanle/src/libcare/tests/fail_threading/.lpmaketmp/patched
mkdir -p /home/hanle/src/libcare/tests/fail_threading/.lpmaketmp/patched || :
cp ./fail_threading    /home/hanle/src/libcare/tests/fail_threading/.lpmaketmp/patched
if test -n ""; then                             \
        cp 4e5f21fed4cfa88550a4cc11e633bd6c2f2c7b31.kpatch /home/hanle/src/libcare/tests/fail_threading/.lpmaketmp/patched;     \
fi
if test -n ""; then                             \
        cp -L  /home/hanle/src/libcare/tests/fail_threading/.lpmaketmp/patched;\
fi
MAKING PATCHES
Fixing up relocation puts@@GLIBC_2.2.5+fffffffffffffffc
patch for /home/hanle/src/libcare/tests/fail_threading/lpmake/fail_threading is in /home/hanle/src/libcare/tests/fail_threading/patchroot/c51f2c6da66aad6f19cde255b49383e24aa31f11.kpatch
awk: cmd. line:4: warning: escape sequence `\.' treated as plain `.'

**Comment by chenzhbao629** [comment]
Thanks paboldin !
