### ISSUE TITLE
How to patch QEMU using libcare?

### ISSUE THREAD

**Issue by fangying** [cloudlinux/libcare#50]
Hi,
I got the "KPCC: cant't find output file, passing through" when using `libcare-patch-make` to make demo patch for qemu. It seems like `libcare-cc` requires obj must be compiled using “cc -o output.o output.c“，however qemu Makefile is not doing compilation in this way.  I cannot make qemu demo patch using `libcare-patch-make`. 
Could please guide us by writting a brief tutorial on how to patch QEMU using libcare ?

 @paboldin @olshanov @loyfan 
Thanks.
Ying

**Comment by loyfan** [comment]
Sorry come late. 
Maybe this #52 solve the problem.
