### ISSUE TITLE
Why can't apply a different patch to the same target process which was already patced

### ISSUE THREAD

**Issue by coryee** [cloudlinux/libcare#54]
When applying patch, libcare-ctl will return immediately if it finds that the target process was already patched, adn i cann't figure out why the sanity check is needed.  I would appreciate it if somebody can explain why?

**Comment by paboldin** [comment]
There is a patchlevel support in libcare-ctl, take a look at patchlevel tests.

**Comment by coryee** [comment]
Thanks @paboldin, I tested and it is what i need
